# Kubernetes管理系统配置文件

# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"

# 数据库配置
database:
  # 数据库类型: sqlite 或 etcd
  type: sqlite
  # SQLite配置
  sqlite:
    path: ./data/kde.db
  # etcd配置
  etcd:
    endpoints:
      - http://localhost:2379
    dialTimeout: 5

# Kubernetes部署配置
deploy:
  # Ansible配置
  ansible:
    inventoryPath: ./configs/ansible/inventory
    playbooksPath: ./pkg/deploy/ansible/playbooks
  # 容器配置
  container:
    registry: docker.io
    namespace: kde

# 应用交付配置
delivery:
  # Helm配置
  helm:
    repoUrl: https://charts.helm.sh/stable
    cachePath: ./data/helm-cache
  # 工作目录
  workdir: ./data/workdir

# 日志配置
log:
  level: "info"
  format: "text"
  output: "stdout"